import type { Question } from '../../types';

type WordProblemTemplate = {
  topic: string;
  semester: 1 | 2;
  prompt: string;
  answer: string;
  unit?: string;
};

export const G2_WORD_PROBLEMS: WordProblemTemplate[] = [
  // HK1 - cộng trừ
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Cửa hàng buổi sáng bán được 23 kg gạo. Buổi chiều bán hơn buổi sáng 10 kg. Hỏi cả ngày bán được bao nhiêu kg gạo?',
    answer: '56',
    unit: 'kg',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Lớp 2A có 32 học sinh, lớp 2B có 28 học sinh. Hỏi cả hai lớp có tất cả bao nhiêu học sinh?',
    answer: '60',
    unit: 'học sinh',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Mẹ có 85 quả cam, mẹ cho em 17 quả. Hỏi mẹ còn lại bao nhiêu quả cam?',
    answer: '68',
    unit: 'quả',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Bin có 25 viên bi, anh trai có nhiều hơn Bin 18 viên. Hỏi anh trai có bao nhiêu viên bi?',
    answer: '43',
    unit: 'viên',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Thùng thứ nhất có 145 ℓ nước, thùng thứ hai ít hơn thùng thứ nhất 38 ℓ. Hỏi thùng thứ hai có bao nhiêu lít nước?',
    answer: '107',
    unit: 'ℓ',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Một mảnh vải dài 87 cm, người ta cắt đi 39 cm. Hỏi mảnh vải còn lại dài bao nhiêu xăng-ti-mét?',
    answer: '48',
    unit: 'cm',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Sáng bán 156 quả trứng, chiều bán thêm 234 quả. Hỏi cả ngày bán được bao nhiêu quả trứng?',
    answer: '390',
    unit: 'quả',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Cô An có 500 nghìn đồng, cô mua quà hết 175 nghìn đồng. Hỏi cô An còn lại bao nhiêu nghìn đồng?',
    answer: '325',
    unit: 'nghìn đồng',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Đoạn dây thứ nhất dài 4 dm 5 cm, đoạn dây thứ hai dài 3 dm 8 cm. Hỏi cả hai đoạn dây dài bao nhiêu xăng-ti-mét?',
    answer: '83',
    unit: 'cm',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Bao gạo nặng 50 kg, bao đường nhẹ hơn bao gạo 18 kg. Hỏi bao đường nặng bao nhiêu ki-lô-gam?',
    answer: '32',
    unit: 'kg',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Cửa hàng buổi sáng bán 250 kg gạo, buổi chiều bán thêm 178 kg. Hỏi cả ngày cửa hàng bán được bao nhiêu ki-lô-gam gạo?',
    answer: '428',
    unit: 'kg',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Bác tài xế buổi sáng lái xe được 245 km, buổi chiều lái thêm 168 km. Hỏi cả ngày bác tài lái được tất cả bao nhiêu ki-lô-mét?',
    answer: '413',
    unit: 'km',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Vườn nhà bà có 280 cây cam và 145 cây bưởi. Hỏi vườn nhà bà có tất cả bao nhiêu cây?',
    answer: '425',
    unit: 'cây',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Thư viện có 425 quyển sách, đã cho học sinh mượn 167 quyển. Hỏi thư viện còn lại bao nhiêu quyển sách?',
    answer: '258',
    unit: 'quyển',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Anh Nam cao 156 cm, em Bình thấp hơn anh Nam 18 cm. Hỏi em Bình cao bao nhiêu xăng-ti-mét?',
    answer: '138',
    unit: 'cm',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Cuộn dây thứ nhất dài 245 m, cuộn dây thứ hai dài hơn cuộn thứ nhất 78 m. Hỏi cuộn dây thứ hai dài bao nhiêu mét?',
    answer: '323',
    unit: 'm',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Ao cá có 612 con cá, người ta bắt đi 248 con. Hỏi trong ao còn lại bao nhiêu con cá?',
    answer: '364',
    unit: 'con',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Đội múa có 36 bạn nữ, số bạn nam ít hơn số bạn nữ 9 bạn. Hỏi đội múa có bao nhiêu bạn nam?',
    answer: '27',
    unit: 'bạn',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Bác đưa thư thứ Bảy phát 175 lá thư, Chủ nhật phát thêm 218 lá. Hỏi cả hai ngày bác đưa thư phát được bao nhiêu lá thư?',
    answer: '393',
    unit: 'lá',
  },
  {
    topic: 'g2-word-add-sub',
    semester: 1,
    prompt: 'Bể nước thứ nhất chứa 320 ℓ nước, bể thứ hai chứa ít hơn bể thứ nhất 95 ℓ. Hỏi bể thứ hai chứa bao nhiêu lít nước?',
    answer: '225',
    unit: 'ℓ',
  },

  // HK2 - nhân chia
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Mỗi bàn có 5 chiếc ghế. Hỏi 7 bàn có tất cả bao nhiêu chiếc ghế?',
    answer: '35',
    unit: 'chiếc',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Một con gà có 2 chân. Hỏi 9 con gà có bao nhiêu chân?',
    answer: '18',
    unit: 'chân',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Có 20 quả cam chia đều cho 5 bạn. Hỏi mỗi bạn được bao nhiêu quả cam?',
    answer: '4',
    unit: 'quả',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Mẹ mua 16 cái bánh, chia đều vào 2 đĩa. Hỏi mỗi đĩa có bao nhiêu cái bánh?',
    answer: '8',
    unit: 'cái',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Một xe ô tô có 4 bánh. Hỏi 5 xe ô tô có tất cả bao nhiêu bánh?',
    answer: '20',
    unit: 'bánh',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Có 30 cái kẹo chia đều cho 5 bạn. Hỏi mỗi bạn được mấy cái kẹo?',
    answer: '6',
    unit: 'cái',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Mỗi hộp có 5 chiếc bút. Hỏi 8 hộp có bao nhiêu chiếc bút?',
    answer: '40',
    unit: 'chiếc',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Lớp có 40 bạn xếp thành 5 hàng đều nhau. Hỏi mỗi hàng có bao nhiêu bạn?',
    answer: '8',
    unit: 'bạn',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Một tuần có 7 ngày. Hỏi 4 tuần có bao nhiêu ngày?',
    answer: '28',
    unit: 'ngày',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Có 18 quả táo chia đều vào các đĩa, mỗi đĩa 2 quả. Hỏi cần bao nhiêu cái đĩa?',
    answer: '9',
    unit: 'đĩa',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Mỗi bông hoa hồng có 5 cánh. Hỏi 6 bông hoa hồng có tất cả bao nhiêu cánh hoa?',
    answer: '30',
    unit: 'cánh',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Mỗi chiếc xe đạp có 2 bánh xe. Hỏi 8 chiếc xe đạp có tất cả bao nhiêu bánh xe?',
    answer: '16',
    unit: 'bánh',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Cô giáo có 45 viên kẹo chia đều cho 5 nhóm học sinh. Hỏi mỗi nhóm được bao nhiêu viên kẹo?',
    answer: '9',
    unit: 'viên',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Có 14 con chim đậu thành 2 hàng đều nhau. Hỏi mỗi hàng có bao nhiêu con chim?',
    answer: '7',
    unit: 'con',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Mỗi túi giấy có 5 quả cam. Hỏi 9 túi như thế có tất cả bao nhiêu quả cam?',
    answer: '45',
    unit: 'quả',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Có 25 chiếc cốc xếp đều vào các khay, mỗi khay 5 chiếc. Hỏi xếp được bao nhiêu cái khay?',
    answer: '5',
    unit: 'khay',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Bố mua 16 quả chuối chia đều cho 2 anh em. Hỏi mỗi người được bao nhiêu quả chuối?',
    answer: '8',
    unit: 'quả',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Mỗi đôi giày có 2 chiếc giày. Hỏi 7 đôi giày có bao nhiêu chiếc giày?',
    answer: '14',
    unit: 'chiếc',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Mỗi con sao biển có 5 cánh. Hỏi 8 con sao biển có tất cả bao nhiêu cánh?',
    answer: '40',
    unit: 'cánh',
  },
  {
    topic: 'g2-word-mul-div',
    semester: 2,
    prompt: 'Có 50 quả táo xếp đều vào các đĩa, mỗi đĩa 5 quả. Hỏi xếp được bao nhiêu cái đĩa?',
    answer: '10',
    unit: 'đĩa',
  },
];

export function getG2WordProblems(topic: string, semester: 1 | 2 | 'all'): Question[] {
  return G2_WORD_PROBLEMS.filter((w) => w.topic === topic && (semester === 'all' || w.semester === semester)).map((w, i) => ({
    id: `g2-wp-${topic}-${i}`,
    grade: 2,
    semester: w.semester,
    topic: w.topic,
    type: 'word-problem' as const,
    prompt: w.prompt,
    answer: w.answer,
    unit: w.unit,
  }));
}
